name: uic_task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  iconly: ^1.0.1
  logger: ^2.5.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1

  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_messaging: ^15.2.7
  cloud_firestore: ^5.6.9

  # Maps (Yandex MapKit)
  #  yandex_mapkit: ^4.1.0
  #  geolocator: ^14.0.1

  equatable: ^2.0.7
  dartz: ^0.10.1
  flutter_svg: ^2.1.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
  bloc_test: ^10.0.0

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: SourceSan
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.otf
